spring:
  datasource:
      url : jdbc:postgresql://192.168.1.250:5432/dlut?useUnicode=true&characterEncoding=UTF-8
      username : postgres
      password : q3nzqd63jrk3gvqmdtzc6ui33mqiefj6
  jpa:
    show-sql : false
    hibernate:
      ddl-auto : update

